---
name: 问题反馈
about: 提交问题缺陷帮助我们更好的改进
title: '[BUG]'
labels: 'bug'
assignees: ''

---

### 依赖环境
*Forest以及相关依赖框架的版本。*

  Forest: version
  Backend: (okhttp或httpclient)/version
  SpringBoot: version (不用就去掉这行)
  Solon: version (不用就去掉这行)

### 问题描述
*请简介清晰地描述问题的状况。*

### 如何复现
*请详细告诉我们如何复现您遇到的问题，并附上可复现的代码示例*

  1.
  2.
  3.
  ```java
  //可在此输入示例代码
  ```
  
### 预期结果
*请告诉我们您预期会发生什么。*

### 实际结果
*请告诉我们实际发生了什么。*


### 截图或视频
*如果可以的话，上传任何关于 Bug 的截图。*


### 最小可复现代码
*如文字无法说清问题或复现过程，可以写一个小 demo 提交到 Gitee 仓库，并贴上仓库地址*
